// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Header
	Message
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Magic   uint32 `protobuf:"varint,1,opt,name=magic" json:"magic,omitempty"`
	SeqNum  uint32 `protobuf:"varint,2,opt,name=seqNum" json:"seqNum,omitempty"`
	ProtoID uint32 `protobuf:"varint,3,opt,name=protoID" json:"protoID,omitempty"`
	MsgID   uint32 `protobuf:"varint,4,opt,name=msgID" json:"msgID,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetMagic() uint32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Header) GetSeqNum() uint32 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *Header) GetProtoID() uint32 {
	if m != nil {
		return m.ProtoID
	}
	return 0
}

func (m *Header) GetMsgID() uint32 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

type Message struct {
	Header  *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Payload []byte  `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "Header")
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe3, 0x62, 0xf3, 0x48, 0x4d,
	0x4c, 0x49, 0x2d, 0x12, 0x12, 0xe1, 0x62, 0xcd, 0x4d, 0x4c, 0xcf, 0x4c, 0x96, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0d, 0x82, 0x70, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x53, 0x0b, 0xfd, 0x4a, 0x73, 0x25,
	0x98, 0xc0, 0xc2, 0x50, 0x9e, 0x90, 0x04, 0x17, 0x3b, 0xd8, 0x00, 0x4f, 0x17, 0x09, 0x66, 0xb0,
	0x04, 0x8c, 0x0b, 0x36, 0xa7, 0x38, 0xdd, 0xd3, 0x45, 0x82, 0x05, 0x6a, 0x0e, 0x88, 0xa3, 0xe4,
	0xc2, 0xc5, 0xee, 0x0b, 0xb1, 0x58, 0x48, 0x9e, 0x8b, 0x2d, 0x03, 0x6c, 0x25, 0xd8, 0x26, 0x6e,
	0x23, 0x76, 0x3d, 0x88, 0x0b, 0x82, 0xa0, 0xc2, 0x60, 0xb3, 0x13, 0x2b, 0x73, 0xf2, 0x13, 0x53,
	0xc0, 0x96, 0xf2, 0x04, 0xc1, 0xb8, 0x49, 0x6c, 0x60, 0x4b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0xd8, 0x25, 0x13, 0xc5, 0x00, 0x00, 0x00,
}
